<!-- Row -->
<div class="row margen-pedido">
  <div class="col-md-12">
    <h2 class="text-center">Editar usuario</h2>
    <div class="form-group">
    <form class="contact-form" id="formulario">
      <div class="row">
        <div class="col-xs-12 col-md-12">
          <input id="id" type="hidden" name="id" value="<?php echo $id ?>">
          <label><b>Nombre</b></label>
          <input id="nombre" name="nombre" class="form-control" placeholder="Nombre">
          <label>Apellido</label>
          <input id="apellido" name="apellido" class="form-control" placeholder="Apellido">
          <label>Correo</label>
          <input id="correo" name="correo" class="form-control" placeholder="Correo">
          <br>
          <input type="submit" class="btn btn-primary" value="Editar Usuario">
        </div>
      </div>
    </form>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    let usuario = $("#id").val();
    $.get('http://localhost/backendfull/api/usuario/'+usuario, function(result){
      $("#nombre").val(result.nombre);
      $("#apellido").val(result.apellido);
      $("#correo").val(result.email);
    });

    $("#formulario").on('submit', function(e){
      e.preventDefault();
      let id = $("#id").val();
      let nombre = $("#nombre").val();
      let apellido = $("#apellido").val();
      let correo = $("#correo").val();
      console.log(formulario);
      $.ajax({
        type: 'put',
        cache: false,
        url: 'http://localhost/backendfull/api/usuario/editarUsuario',
        data: {"id": id, "nombre":nombre, "apellido":apellido, "correo":correo},
        success: function(result){
          if(result){
            swal({
                        icon: 'success',
                        title: 'Usuario editado',
                        text: 'Será redireccionado...',
                        closeOnClickOutside: false,
                        button: {
                text: "Ok",
                visible: false,
                          },
                        timer: 3000
                  }).then(function() {
                    swal.close();
                    window.location.href = "<?php echo PUBLIC_PATH.'usuario/ver' ?>";
                  })
          }else{
            swal({
  		                  icon: 'error',
  		                  title: 'Error al editar el usuario',
  		                  button: {
  								      text: "Ok",
  								      visible: false,
  		                      },
  		                  closeOnClickOutside: false,
  		                  timer: 1500
  		              })
          }
        }
      })
    })
  })
</script>
