
    <div class="row ">

      <!-- home content -->
      <div class="col-md-3"></div>
      <div class="col-md-6">
          <h1 class="text-center">Aplicación de gestión de usuarios</h1>
          <h4 class="text-center">Sistema web de usuarios
          </h4>
          <div class="text-center">
            <?php echo Html::link('usuario/ver', 'Buscar usuario', 'class="btn btn-primary"')  ?>
          </div>
      </div>
      <div class="col-md-3"></div>
      <!-- /home content -->

    </div>
