<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>Sistema de solicitud de usuarios</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="http://localhost/libreria/img/favicon.png">
  <?php //Tag::css('bootstrap.min') ?>
  <?php Tag::css('font-awesome.min') ?>
  <?php Tag::css('cosmo') ?>
  <?php //Tag::css('style') ?>
  <?php Tag::css('libreria') ?>
  <?= Html::includeCss() ?>
  <?php echo Tag::js('jquery.min') ?>
</head>
<body class="fondo_pedido">
  <?php View::partial('app/header') ?>
  <div class="container">
    <?php View::content() ?>
  </div>
  <!-- jQuery Plugins -->

  <?php echo Tag::js('bootstrap.min') ?>
  <?php echo Tag::js('owl.carousel.min') ?>
  <?php echo Tag::js('jquery.magnific-popup') ?>
  <?php echo Tag::js('main') ?>
  <?php echo Tag::js('sweetalert') ?>
</body>
</html>
